"""
Cria automaticamente as tabelas do EqualMind com sufixo _WorkWell
"""
import cx_Oracle
from config import Config
import logging

logger = logging.getLogger(__name__)

def insert_initial_data(cursor, connection):
    """Insere dados iniciais de exemplo"""
    
    # Verificar se já existe empresa com ID 1
    cursor.execute("SELECT COUNT(*) FROM EMPRESAS_WorkWell WHERE ID = 1")
    empresa_exists = cursor.fetchone()[0] > 0
    
    if empresa_exists:
        logger.info("ℹ️ Dados iniciais já existem (pulando)")
        return
    
    # Inserir empresa
    try:
        cursor.execute("""
            INSERT INTO EMPRESAS_WorkWell (NOME, CNPJ) 
            VALUES ('FIAP Tecnologia S.A.', '12.345.678/0001-99')
        """)
        connection.commit()
        logger.info("✅ Empresa inserida")
    except cx_Oracle.Error as e:
        error_obj, = e.args
        if error_obj.code == 1:  # Unique constraint violation
            logger.info("ℹ️ Empresa já existe")
        else:
            logger.warning(f"⚠️ Erro ao inserir empresa: {error_obj.message}")
        connection.rollback()
    
    # Inserir setores
    setores = [
        (1, 'Desenvolvimento', 'Equipe de desenvolvimento de software'),
        (1, 'Recursos Humanos', 'Gestão de pessoas e cultura'),
        (1, 'Marketing', 'Estratégias de comunicação'),
        (1, 'Engenharia', 'Equipe de engenharia'),
        (1, 'Financeiro', 'Contabilidade e Finanças')
    ]
    
    for empresa_id, nome, descricao in setores:
        try:
            cursor.execute("""
                INSERT INTO SETORES_WorkWell (EMPRESA_ID, NOME, DESCRICAO) 
                VALUES (:1, :2, :3)
            """, (empresa_id, nome, descricao))
            connection.commit()
            logger.info(f"✅ Setor '{nome}' inserido")
        except cx_Oracle.Error as e:
            error_obj, = e.args
            if error_obj.code == 1:  # Unique constraint violation
                logger.info(f"ℹ️ Setor '{nome}' já existe")
            else:
                logger.warning(f"⚠️ Erro ao inserir setor '{nome}': {error_obj.message}")
            connection.rollback()
    
    # Inserir colaboradores
    colaboradores = [
        (1, 1, 'FIAPDEV001', 'João Silva'),
        (1, 1, 'FIAPDEV002', 'Maria Santos'),
        (1, 2, 'FIAPRH001', 'Pedro Oliveira'),
        (1, 3, 'FIAPMKT001', 'Ana Costa')
    ]
    
    for empresa_id, setor_id, codigo, nome in colaboradores:
        try:
            cursor.execute("""
                INSERT INTO COLABORADORES_WorkWell (EMPRESA_ID, SETOR_ID, CODIGO_ACESSO) 
                VALUES (:1, :2, :3)
            """, (empresa_id, setor_id, codigo))
            connection.commit()
            logger.info(f"✅ Colaborador '{codigo}' inserido")
        except cx_Oracle.Error as e:
            error_obj, = e.args
            if error_obj.code == 1:  # Unique constraint violation
                logger.info(f"ℹ️ Colaborador '{codigo}' já existe")
            else:
                logger.warning(f"⚠️ Erro ao inserir colaborador '{codigo}': {error_obj.message}")
            connection.rollback()
    
    logger.info("✅ Dados iniciais inseridos com sucesso!")

def create_tables_if_not_exist(connection):
    """Cria as tabelas automaticamente se não existirem"""
    cursor = connection.cursor()
    
    tables_sql = [
        # Tabela de Empresas
        """CREATE TABLE EMPRESAS_WorkWell (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            NOME VARCHAR2(255) NOT NULL,
            CNPJ VARCHAR2(18) UNIQUE NOT NULL,
            DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )""",
        
        # Tabela de Setores
        """CREATE TABLE SETORES_WorkWell (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            EMPRESA_ID NUMBER NOT NULL,
            NOME VARCHAR2(255) NOT NULL,
            DESCRICAO VARCHAR2(500),
            CONSTRAINT FK_SETOR_EMPRESA_WW FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS_WorkWell(ID)
        )""",
        
        # Tabela de Colaboradores
        """CREATE TABLE COLABORADORES_WorkWell (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            EMPRESA_ID NUMBER NOT NULL,
            SETOR_ID NUMBER,
            CODIGO_ACESSO VARCHAR2(255) UNIQUE NOT NULL,
            DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT FK_COLAB_EMPRESA_WW FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS_WorkWell(ID),
            CONSTRAINT FK_COLAB_SETOR_WW FOREIGN KEY (SETOR_ID) REFERENCES SETORES_WorkWell(ID)
        )""",
        
        # Tabela de Registros Emocionais
        """CREATE TABLE REGISTROS_EMOCIONAIS_WorkWell (
            ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            COLABORADOR_ID NUMBER,
            EMPRESA_ID NUMBER NOT NULL,
            SETOR_ID NUMBER NOT NULL,
            NIVEL_ESTRESSE NUMBER(2) NOT NULL,
            NIVEL_FELICIDADE NUMBER(2) NOT NULL,
            NIVEL_ANSIEDADE NUMBER(2) DEFAULT 5 NOT NULL,
            NIVEL_MOTIVACAO NUMBER(2) DEFAULT 5 NOT NULL,
            COMENTARIO VARCHAR2(1000),
            SENTIMENTO_TEXTO VARCHAR2(50),
            SCORE_SENTIMENTO NUMBER(5,2),
            DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT CK_ESTRESSE CHECK (NIVEL_ESTRESSE BETWEEN 1 AND 10),
            CONSTRAINT CK_FELICIDADE CHECK (NIVEL_FELICIDADE BETWEEN 1 AND 10),
            CONSTRAINT CK_ANSIEDADE CHECK (NIVEL_ANSIEDADE BETWEEN 1 AND 10),
            CONSTRAINT CK_MOTIVACAO CHECK (NIVEL_MOTIVACAO BETWEEN 1 AND 10),
            CONSTRAINT FK_REG_COLAB_WW FOREIGN KEY (COLABORADOR_ID) REFERENCES COLABORADORES_WorkWell(ID),
            CONSTRAINT FK_REG_EMPRESA_WW FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESAS_WorkWell(ID),
            CONSTRAINT FK_REG_SETOR_WW FOREIGN KEY (SETOR_ID) REFERENCES SETORES_WorkWell(ID)
        )"""
    ]
    
    logger.info("Verificando e criando tabelas...")
    
    # Nomes das tabelas para logs
    table_names = ["EMPRESAS_WorkWell", "SETORES_WorkWell", "COLABORADORES_WorkWell", "REGISTROS_EMOCIONAIS_WorkWell"]
    
    # Criar tabelas (se não existirem) - uma por vez com commit
    for i, sql in enumerate(tables_sql, 1):
        table_name = table_names[i-1]
        try:
            cursor.execute(sql)
            connection.commit()
            logger.info(f"✅ Tabela {i}/4 ({table_name}) criada com sucesso")
        except cx_Oracle.Error as e:
            error_obj, = e.args
            if error_obj.code == 955:  # Tabela já existe
                logger.info(f"ℹ️ Tabela {i}/4 ({table_name}) já existe (pulando)")
                connection.commit()  # Garantir commit mesmo se já existe
            else:
                logger.error(f"❌ Erro ao criar tabela {i}/4 ({table_name}): {error_obj.message}")
                logger.error(f"   Código do erro: {error_obj.code}")
                connection.rollback()  # Rollback em caso de erro
                # Continuar tentando criar as outras tabelas
    
    # Inserir dados iniciais (se não existirem)
    logger.info("Inserindo dados iniciais...")
    try:
        insert_initial_data(cursor, connection)
    except Exception as e:
        logger.warning(f"⚠️ Erro ao inserir dados iniciais (continuando): {e}")
    
    cursor.close()
    logger.info("✅ Verificação de tabelas e dados concluída!")

